### ISSUE TITLE
Compliance with AGPLv3

### ISSUE THREAD

**Issue by 2mac** [justyntemme/coinserve#1]
The license of coinfetch and the cfetch module is version 3 of the GNU Affero General Public License. One of the requirements thereof is that network interfaces have to expose the source of the AGPL-covered work.

Thus, this program needs to have some API call which can give a URL pointing to the source of the version you're running. This also needs to be done with any web frontends you make for this.

**Comment by justyntemme** [comment]
Does this need to point to the source of my work or cfetch?

**Comment by 2mac** [comment]
It can do both, but you are required by the AGPL to at least expose the source of the version of cfetch you are using. If you run a modified version of it on your server, it must link to a copy of that version, not the original.

**Comment by justyntemme** [comment]
Issue is Fixed. Client just has to send a string to the server to receive URL to github repo.

**Comment by 2mac** [comment]
One more thing, possibly, would be to add a `help` call that would explain the options (including the source request).
