### ISSUE TITLE
Please add license headers

### ISSUE THREAD

**Issue by 2mac** [justyntemme/coinserve#2]
The GPL recommends using license headers in your source code (see the headers in the coinfetch source code for reference) so that anyone reading the source knows the license of any given file.

In a repo like this, it's pretty easy to tell that the LICENSE file declares the license, but if someone wanted to take a particular file from this repo and copy it into a new work, you'll want your copyright statement and license info to go with it.

**Comment by justyntemme** [comment]
Fixed in commit 40bcc6a7358c38a6fdef1aa238f5fefee60d2256

**Comment by 2mac** [comment]
Watch out! Looks like you copied my headers verbatim. My program is under the **AGPL**. Your LICENSE file says that you're using the **GPL**. There is an important difference. Either change your headers to be for the regular GPL, or change your LICENSE file to be the AGPL.

**Comment by justyntemme** [comment]
Okay, should be fixed. If there is any issue let me know i'll get it changed. Thanks for your help.
