### ISSUE TITLE
Please make an install script

### ISSUE THREAD

**Issue by 2mac** [justyntemme/coinserve#3]
Read up on the `setuptools` module for Python 3 and use it to make an install script for your program. Having to run it in a particular directory is annoying for someone who might actually want to deploy this on a real server.

I recommend doing like I did with coinfetch and splitting the heavy lifting into a package (like `cfetch`) and having a single executable file (like `coinfetch`) to start the service. If you're really nice, you can make a systemd service file for full automation, but that's not as imperative as the regular install script.

**Comment by justyntemme** [comment]
Install script created. Now i can launch it right from the terminal :)

**Comment by 2mac** [comment]
Your install script includes a package `cfetch` that is not present in the repo. You should set the `cfetch` module as a dependency instead of saying it's part of this program. Look at the way `coinfetch` uses `requests` as a dependency, and do likewise for `cfetch` in your script.
